name: test dispatch

on:
  push:
    branches: 
      - main


jobs:
  dispatch:
    name: dispatch
    steps:
      - name: dispatch
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GHA_WORKFLOW_DISPATCH }}
          script: |
            const result = await github.rest.actions.createWorkflowDispatch({
              owner: 'rladies',
              repo: 'website',
              workflow_id: 'build_site.yaml',
              ref: 'main'
            })
            console.log(result)
            