name: Get meetup data

on:
  pull_request:
    branches:
      - main
  push:
    branches: 
      - main
  schedule:
    - cron: "0 */12 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
jobs:
  meetup:
    name: Update meetup data
    runs-on: ubuntu-latest
    env: 
      MEETUPR_PWD: ${{ secrets.MEETUPR_PWD }}
      RENV_PATHS_ROOT: ~/.local/share/renv
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Install cURL Headers
        run: |
          sudo apt-get update
          sudo apt-get install libcurl4-openssl-dev libsodium-dev
        
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          version: 'renv'

      - name: Setup renv
        uses: r-lib/actions/setup-renv@v2
          
      - name: Meetup authentication
        run:  Rscript scripts/meetup_auth.R
        
      - name: Update chapter data
        run:  Rscript scripts/get_chapters.R
        
      - name: Update event data
        run:  Rscript scripts/get_events.R
        
      - name: Commit data	
        if: github.event_name == 'schedule' || github.event_name == 'push'
        run: |	
          git config --local user.email "actions@github.com"	
          git config --local user.name "GitHub Actions"	
          git add data/	
          git commit -m 'Update meetup data' || echo "No meetup data to commit"	
          git push || echo "Nothing to push"	
