name: Render and Publish Quarto Reports

on:
  push:
    branches:
      - main
    paths:
      - "reports/**"
      - "data/**"
      - "_quarto.yml"
      - "renv.lock"
  workflow_dispatch:
  schedule:
    - cron: "05 23 1 */3 *"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  render-and-deploy:
    runs-on: ubuntu-latest
    env:
      RENV_PATHS_ROOT: ~/.cache/R/renv
      RENV_PROFILE: reports
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: "release"

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: "renv"

      - name: Cache packages
        uses: actions/cache@v4
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-

      - name: Restore packages
        shell: Rscript {0}
        run: |
          if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
          renv::restore()

      - name: Render Quarto reports
        run: |
          quarto render reports/ --to all

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./docs/reports/"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
